include $(RHOME)/src/gnuwin32/MkRules

all: Rigroup.dll

DLLNAME = Rigroup

OBJS = Rigroup.o Rinit.o
CFLAGS =  -I$(RHOME)/src/include -O2 -DWin32
DLLLIBS = -L$(RHOME)/bin -lrpcrt4 -lg2c -lRblas -lR

$(DLLNAME).a: $(OBJS)
	$(RM) -f $@
	$(AR) cr $@ *.o
	$(RANLIB) $@

$(DLLNAME).dll : $(DLLNAME).a

clean:
	$(RM) $(DLLNAME).dll *.a $(OBJS) $(DLLNAME).def
